export enum SceneID {
	none = "none",
	splash = "splash",
	mainpage = "mainpage",
	mp_home = "mp_home",
	mp_enterprise = "mp_enterprise",
	mp_offer = "mp_offer",
	mp_service = "mp_service",
	mp_profile = "mp_profile",
	mp_favorite = "mp_favorite",
	mp_filter = "mp_filter",
	mp_field = "mp_field",
	mp_example = "mp_example",
	mp_casefilter = "mp_casefilter",
	mp_fielddetail = "mp_fielddetail",
	detail = "detail",
	dt_brief = "dt_brief",
	dt_field = "dt_field",
	dt_info = "dt_info",
	dt_offer = "dt_offer",
	dt_example = "dt_example",
	lm_aizhushou = "lm_aizhushou",
	lm_qiuzhiziliao = "lm_qiuzhiziliao",
	lm_shixineitui = "lm_shixineitui",
	lm_gangweineitui = "lm_gangweineitui",
	lm_bishitiku = "lm_bishitiku",
	lm_qiuzhifuwu = "lm_qiuzhifuwu",
	lm_mianshijingyan = "lm_mianshijingyan",
	lm_zixunguwen = "lm_zixunguwen",
	kefu = "kefu",
}

export enum EventType {
	none = "none",
	mainpage_activate = "mainpage_activate",
	mainpage_example_casefilter = "mainpage_example_casefilter",
}
